---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/widgets

#- resources:
#    cpu: true
#    memory: true
#    disk: /

- logo:
    icon: https://raw.githubusercontent.com/sloraris/logos/main/slo-home.png
    
- openmeteo:
    label: Logan # optional
    latitude: 41.737878
    longitude: -111.830846
    timezone: America/Boise # optional
    units: imperial # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
