---
- name: Recursive DNS Server
  hosts: server_dns
  become: yes
  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install prerequisites
      apt:
        name:
          - wget
          - git
          - tar
          - dnsutils
          - unbound
        state: present

    - name: Download server_dns config files to temporary location
      git:
        repo: 'https://github.com/sloraris/ORBIT2.0/server_dns.git'
        dest: ~/config-tmp
        version: master
        force: yes

    - name: Copy Unbound config file to the appropriate location
      copy:
        src: ~/config-tmp/unbound.conf
        dest: /etc/unbound/unbound.conf.d/pi-hole.conf
        owner: root
        group: root
        mode: '0644'

    - name: Check if unbound-resolvconf service is active
      command: systemctl is-active unbound-resolvconf.service
      register: unbound_resolvconf_status
      ignore_errors: yes

    - name: Disable unbound-resolvconf service
      service:
        name: unbound-resolvconf
        state: stopped
        enabled: no
      when: unbound_resolvconf_status.stdout == "active"


    - name: Restart Unbound service
      service:
        name: unbound
        state: restarted
        enabled: yes

    - name: Install AdGuard Home
      shell: |
        wget 'https://static.adguard.com/adguardhome/release/AdGuardHome_linux_armv6.tar.gz'
        tar -xf AdGuardHome_linux_armv6.tar.gz
        cd AdGuardHome
        ./AdGuardHome -s install
      args:
        chdir: ~

    - name: Copy AdGuard config file to the appropriate location
      copy:
        src: ~/config-tmp/AdGuardHome.yaml
        dest: ~/AdGuardHome/AdGuardHome.yaml
        owner: root
        group: root
        mode: '0644'

    - name: Clean up cloned repository
      file:
        path: ~/config-tmp
        state: absent

    - name: Change set password for AdGuard
      lineinfile:
        path: ~/AdGuardHome/AdGuardHome.yaml
        regexp: '^password:.*'
        line: "password: {{ adguard_pswd }}"
        state: present

    - name: Start AdGuard Home
      service:
        name: AdGuardHome
        state: started
        enabled: yes
