---
# Tasks to install or repair AdGuard Home


# Check for existing adguard install
- name: Check for adguard install
  ansible.builtin.service:
    name: AdGuardHome
    state: present
  register: ag_service_exists

# Check if adguard is running
- name: Check state of adguard service
  ansible.builtin.service:
    name: AdGuardHome
    state: started
  register: ag_service_running
  when: not ag_service_exists

# Check if adguard archive has been downloaded
- name: Check for adguard archive
  ansible.builtin.stat:
    path: "{{ adguard_archive_location }}"
  register: ag_archive_stat
  when: not ag_service_exists

## Download AdGuard if not already on the device (if package is not already downloaded)
- name: Download AdGuardHome archive
  ansible.builtin.get_url:
    url: "{{ adguard_src_url }}"
    dest: "{{ adguard_archive_location }}"
    mode: "0644"
  when: not ag_archive_stat.stat.exists

# Check if adguard directory exists
- name: Check for adguard directory
  ansible.builtin.stat:
    path: "{{ adguard_dir_location }}"
  register: ag_dir_stat
  when: not ag_service_exists

## Create AdGuard directory (if it does not already exist)
- name: Unpack AdGuardHome archive
  ansible.builtin.unarchive:
    src: "{{ adguard_archive_location }}"
    dest: "{{ adguard_dir_location }}"
    extra_opts:
      - ['--strip=1']
  when: not adguard_dir_stat.stat.exists

# TODO: Check if device DNS settings are correct

## Run install script if adguard does not exist
- name: Install AdGuardHome
  ansible.builtin.command:
    cmd: AdGuardHome -s install
    chdir: "{{ adguard_dir_location }}"
    creates: "{{ adguard_service }}"
  when: not ag_service_exists
  notify: Start AdGuardHome
