---
# tasks file for adguard

- name: Install AdGuardHome
  ansible.builtin.include_tasks:
    file: adguard_install.yml

- name: Configure AdGuardHome
  ansible.builtin.include_tasks:
    file: adguard_config.yml

- name: Remove AdGuardHome
  ansible.builtin.include_tasks:
    file: adguard_uninstall.yml
