---
# tasks file for adguard

- name: Install AdGuardHome
  ansible.builtin.include_tasks:
    - adguard_install.yml

- name: Configure AdGuardHome
  ansible.builtin.include_tasks:
    - adguard_config.yml

- name: Remove AdGuardHome
  ansible.builtin.include_tasks:
    - adguard_uninstall.yml
