---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Launchpad
favicon: https://raw.githubusercontent.com/sloraris/logos/main/slo-home.png
theme: dark
color: slate
#background: https://images.unsplash.com/photo-1686519093104-3140c6dcf284?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
#background: https://wallpapercave.com/wp/wp5187908.jpg
background: https://images.unsplash.com/photo-1533134486753-c833f0ed4866?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
cardBlur: xl
headerStyle: clean
fiveColumns: True
hideVersion: True
hideErrors: True


layout:
  Quicklinks:
    header: False
    style: row
    columns: 5
  Uptime-Docker-Servers:
    header: False
    style: row
    columns: 4
  Minecraft-aux:
    header: False
  Minecraft1:
    header: False
  Media:
    header: False
    style: row
    columns: 3
  Network:
    header: False
    style: row
    columns: 3
  NAS:
    header: False
    style: row
    columns: 2

  Bookmarks:
    header: False
    style: row
    columns: 3

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey