galaxy_info:
  author: sloraris
  description: "installs adguard on a raspberry pi"
  license: MIT
  min_ansible_version: '2.1'
  platforms:
    - name: Debian
      version: bullseye


  galaxy_tags:
    - adguard
    - adblock
