---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Quicklinks:
    - Wazuh:
        - abbr: WA
          icon: mdi-shield-lock-#ffffff
          href: https://37.37.2.10:8443
          description: SIEM
    - Cloudflare:
        - abbr: CF
          icon: si-cloudflare-#ffffff
          href: https://dash.cloudflare.com/9aeb475840cb6ef0e64d7e220e3b834e/sloraris.dev
          description: sloraris.dev
    - Github:
        - abbr: GH
          icon: si-github-#ffffff
          href: https://github.com/sloraris?tab=repositories
          description: my repos
    - Command:
        - abbr: CO
          icon: mdi-apple-keyboard-command-#ffffff
          href: http://37.37.2.10:82/#
          description: CasaOS
