name: wazuh
services:
  wazuh.dashboard:
    depends_on:
      wazuh.indexer:
        condition: service_started
        required: true
      wazuh.manager:
        condition: service_started
        restart: true
        required: true
    environment:
      - API_PASSWORD=MyS3cr37P450r.*-
      - API_USERNAME=wazuh-wui
      - DASHBOARD_PASSWORD=kibanaserver
      - DASHBOARD_USERNAME=kibanaserver
      - INDEXER_PASSWORD=SecretPassword
      - INDEXER_USERNAME=admin
      - WAZUH_API_URL=https://wazuh.manager
    hostname: wazuh.dashboard
    image: wazuh/wazuh-dashboard:4.6.0
    links:
      - wazuh.indexer:wazuh.indexer
      - wazuh.manager:wazuh.manager
    ports:
      - mode: ingress
        target: 5601
        published: "8443"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /home/parker/wazuh-docker/single-node/config/wazuh_indexer_ssl_certs/wazuh.dashboard.pem
        target: /usr/share/wazuh-dashboard/certs/wazuh-dashboard.pem
        bind:
          create_host_path: true
      - type: bind
        source: /home/parker/wazuh-docker/single-node/config/wazuh_indexer_ssl_certs/wazuh.dashboard-key.pem
        target: /usr/share/wazuh-dashboard/certs/wazuh-dashboard-key.pem
        bind:
          create_host_path: true
      - type: bind
        source: /home/parker/wazuh-docker/single-node/config/wazuh_indexer_ssl_certs/root-ca.pem
        target: /usr/share/wazuh-dashboard/certs/root-ca.pem
        bind:
          create_host_path: true
      - type: bind
        source: /home/parker/wazuh-docker/single-node/config/wazuh_dashboard/opensearch_dashboards.yml
        target: /usr/share/wazuh-dashboard/config/opensearch_dashboards.yml
        bind:
          create_host_path: true
      - type: bind
        source: /home/parker/wazuh-docker/single-node/config/wazuh_dashboard/wazuh.yml
        target: /usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml
        bind:
          create_host_path: true
      - type: volume
        source: "[object Object]"
        target: /usr/share/wazuh-dashboard/data/wazuh/config
        volume: {}
      - type: volume
        source: "[object Object]"
        target: /usr/share/wazuh-dashboard/plugins/wazuh/public/assets/custom
        volume: {}
    devices: []
    cap_add: []
    command: []
    networks:
      - default
    privileged: false
    container_name: ""
    cpu_shares: 90
    deploy:
      resources:
        limits:
          memory: 7715M
  wazuh.indexer:
    environment:
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    hostname: wazuh.indexer
    image: wazuh/wazuh-indexer:4.6.0
    ports:
      - mode: ingress
        target: 9200
        published: "9200"
        protocol: tcp
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - type: volume
        source: "[object Object]"
        target: /var/lib/wazuh-indexer
        volume: {}
      - type: bind
        source: /home/parker/wazuh-docker/single-node/config/wazuh_indexer_ssl_certs/root-ca.pem
        target: /usr/share/wazuh-indexer/certs/root-ca.pem
        bind:
          create_host_path: true
      - type: bind
        source: /home/parker/wazuh-docker/single-node/config/wazuh_indexer_ssl_certs/wazuh.indexer-key.pem
        target: /usr/share/wazuh-indexer/certs/wazuh.indexer.key
        bind:
          create_host_path: true
      - type: bind
        source: /home/parker/wazuh-docker/single-node/config/wazuh_indexer_ssl_certs/wazuh.indexer.pem
        target: /usr/share/wazuh-indexer/certs/wazuh.indexer.pem
        bind:
          create_host_path: true
      - type: bind
        source: /home/parker/wazuh-docker/single-node/config/wazuh_indexer_ssl_certs/admin.pem
        target: /usr/share/wazuh-indexer/certs/admin.pem
        bind:
          create_host_path: true
      - type: bind
        source: /home/parker/wazuh-docker/single-node/config/wazuh_indexer_ssl_certs/admin-key.pem
        target: /usr/share/wazuh-indexer/certs/admin-key.pem
        bind:
          create_host_path: true
      - type: bind
        source: /home/parker/wazuh-docker/single-node/config/wazuh_indexer/wazuh.indexer.yml
        target: /usr/share/wazuh-indexer/opensearch.yml
        bind:
          create_host_path: true
      - type: bind
        source: /home/parker/wazuh-docker/single-node/config/wazuh_indexer/internal_users.yml
        target: /usr/share/wazuh-indexer/opensearch-security/internal_users.yml
        bind:
          create_host_path: true
    devices: []
    cap_add: []
    command: []
    networks:
      - default
    privileged: false
    container_name: ""
    cpu_shares: 90
    deploy:
      resources:
        limits:
          memory: 7715M
  wazuh.manager:
    environment:
      - API_PASSWORD=MyS3cr37P450r.*-
      - API_USERNAME=wazuh-wui
      - FILEBEAT_SSL_VERIFICATION_MODE=full
      - INDEXER_PASSWORD=SecretPassword
      - INDEXER_URL=https://wazuh.indexer:9200
      - INDEXER_USERNAME=admin
      - SSL_CERTIFICATE=/etc/ssl/filebeat.pem
      - SSL_CERTIFICATE_AUTHORITIES=/etc/ssl/root-ca.pem
      - SSL_KEY=/etc/ssl/filebeat.key
    hostname: wazuh.manager
    image: wazuh/wazuh-manager:4.6.0
    ports:
      - mode: ingress
        target: 1514
        published: "1514"
        protocol: tcp
      - mode: ingress
        target: 1515
        published: "1515"
        protocol: tcp
      - mode: ingress
        target: 514
        published: "514"
        protocol: udp
      - mode: ingress
        target: 55000
        published: "55000"
        protocol: tcp
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    volumes:
      - type: volume
        source: "[object Object]"
        target: /var/ossec/api/configuration
        volume: {}
      - type: volume
        source: "[object Object]"
        target: /var/ossec/etc
        volume: {}
      - type: volume
        source: "[object Object]"
        target: /var/ossec/logs
        volume: {}
      - type: volume
        source: "[object Object]"
        target: /var/ossec/queue
        volume: {}
      - type: volume
        source: "[object Object]"
        target: /var/ossec/var/multigroups
        volume: {}
      - type: volume
        source: "[object Object]"
        target: /var/ossec/integrations
        volume: {}
      - type: volume
        source: "[object Object]"
        target: /var/ossec/active-response/bin
        volume: {}
      - type: volume
        source: "[object Object]"
        target: /var/ossec/agentless
        volume: {}
      - type: volume
        source: "[object Object]"
        target: /var/ossec/wodles
        volume: {}
      - type: volume
        source: "[object Object]"
        target: /etc/filebeat
        volume: {}
      - type: volume
        source: "[object Object]"
        target: /var/lib/filebeat
        volume: {}
      - type: bind
        source: /home/parker/wazuh-docker/single-node/config/wazuh_indexer_ssl_certs/root-ca-manager.pem
        target: /etc/ssl/root-ca.pem
        bind:
          create_host_path: true
      - type: bind
        source: /home/parker/wazuh-docker/single-node/config/wazuh_indexer_ssl_certs/wazuh.manager.pem
        target: /etc/ssl/filebeat.pem
        bind:
          create_host_path: true
      - type: bind
        source: /home/parker/wazuh-docker/single-node/config/wazuh_indexer_ssl_certs/wazuh.manager-key.pem
        target: /etc/ssl/filebeat.key
        bind:
          create_host_path: true
      - type: bind
        source: /home/parker/wazuh-docker/single-node/config/wazuh_cluster/wazuh_manager.conf
        target: /wazuh-config-mount/etc/ossec.conf
        bind:
          create_host_path: true
    devices: []
    cap_add: []
    command: []
    networks:
      - default
    privileged: false
    container_name: ""
    cpu_shares: 90
    deploy:
      resources:
        limits:
          memory: 7715M
networks:
  default:
    name: wazuh_default
volumes:
  filebeat_etc:
    name: wazuh_filebeat_etc
  filebeat_var:
    name: wazuh_filebeat_var
  wazuh-dashboard-config:
    name: wazuh_wazuh-dashboard-config
  wazuh-dashboard-custom:
    name: wazuh_wazuh-dashboard-custom
  wazuh-indexer-data:
    name: wazuh_wazuh-indexer-data
  wazuh_active_response:
    name: wazuh_wazuh_active_response
  wazuh_agentless:
    name: wazuh_wazuh_agentless
  wazuh_api_configuration:
    name: wazuh_wazuh_api_configuration
  wazuh_etc:
    name: wazuh_wazuh_etc
  wazuh_integrations:
    name: wazuh_wazuh_integrations
  wazuh_logs:
    name: wazuh_wazuh_logs
  wazuh_queue:
    name: wazuh_wazuh_queue
  wazuh_var_multigroups:
    name: wazuh_wazuh_var_multigroups
  wazuh_wodles:
    name: wazuh_wazuh_wodles
x-casaos:
  hostname: ""
  scheme: http
  index: /
  port_map: ""
  author: self
  category: self
  icon: ""
  title:
    custom: ""
