---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Network:
    - NGINX:
        icon: nginx-proxy-manager
        href:
        description:
        widget:
            type: npm
            url:
            username:
            password:
    - OPNSense:
        icon: opnsense
        href:
        description:
        widget:
            type: opnsense
            url:
            username: 
            password:
    - Adguard:
        icon: adguard-home
        href:
        description:
        widget:
            type: adguard
            url:
            fields: ["queries", "blocked"]
            username:
            password:


- Uptime-Docker-Servers:
    - Uptime:
        icon: uptime-kuma
        href:
        description:
        widget:
            type: uptimekuma
            url:
            slug:
    - Dockge:
        icon: docker
        href:
        description:
        widget:
          type: dockge
          url:
    - Proxmox:
        icon: proxmox
        href:
        description:
        widget:
            type: proxmox
            url:
            fields: ["vms", "resources.cpu", "resources.mem"]
            username:
            password:
            node:
    - Longhaul:
        icon: truenas
        href:
        description:
        widget:
          type: truenas
          fields: ["load", "uptime"]
          url:
          key:


- NAS:
    - Nextcloud:
        icon: https://raw.githubusercontent.com/sloraris/logos/main/slo-cloud.png
        href:
        description:
        widget:
          type: nextcloud
          url: https://37.37.3.10:9001/ocs/v2.php/apps/serverinfo/api/v1/info?format=json
          fields: ["freespace", "activeusers"]
          username:
          password:
    - Immich:
        icon: immich
        href:
        description:
        widget:
          type: immich
          url:
          key:


- Minecraft1:
    - Velocity:
        icon: https://raw.githubusercontent.com/sloraris/mc-dev-stuff/main/block.PNG
        href:
        description:
        widget:
          type: minecraft
          fields: ["status"]
          url:
- Minecraft-aux:
    - MC CasaOS:
          icon: casaos
          href:
    - MC Editor:
          icon: vscode
          href:
