name: big-bear-dockge
services:
  app:
    container_name: big-bear-dockge
    environment:
      - DOCKGE_STACKS_DIR=/DATA/AppData/big-bear-dockge/stacks
    image: louislam/dockge:1
    labels:
      icon: https://github.com/louislam/dockge/raw/master/frontend/public/icon.svg
    ports:
      - mode: ingress
        target: 5001
        published: "5001"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        bind:
          create_host_path: true
      - type: bind
        source: /DATA/AppData/big-bear-dockge/data
        target: /app/data
        bind:
          create_host_path: true
      - type: bind
        source: /DATA/AppData/big-bear-dockge/stacks
        target: /DATA/AppData/big-bear-dockge/stacks
        bind:
          create_host_path: true
    x-casaos:
      ports:
        - container: "5001"
          description:
            en_us: "Container Port: 5001"
      volumes:
        - container: /var/run/docker.sock
          description:
            en_us: "Container Path: /var/run/docker.sock"
        - container: /app/data
          description:
            en_us: "Container Path: /app/data"
        - container: /DATA/AppData/big-bear-dockge/stacks
          description:
            en_us: "Container Path: /DATA/AppData/big-bear-dockge/stacks"
    devices: []
    cap_add: []
    command: []
    networks:
      - default
    privileged: false
    cpu_shares: 90
    deploy:
      resources:
        limits:
          memory: 7715M
networks:
  default:
    name: big-bear-dockge_default
x-casaos:
  architectures:
    - amd64
    - arm64
  author: BigBearTechWorld
  category: BigBearCasaOS
  description:
    en_us: A fancy, easy-to-use and reactive docker `compose.yaml` stack-oriented
      manager
  developer: louislam
  icon: https://github.com/louislam/dockge/raw/master/frontend/public/icon.svg
  main: app
  port_map: "5001"
  store_app_id: big-bear-dockge
  tagline:
    en_us: Dockge
  thumbnail: ""
  title:
    en_us: Dockge
    custom: ""
  hostname: ""
  scheme: http
  index: /
