# server_dns
unbound_config_url: https://raw.githubusercontent.com/sloraris/ORBIT2.0/main/server_dns/pi-hole.conf
adguard_config_url: https://raw.githubusercontent.com/sloraris/ORBIT2.0/main/server_dns/AdGuardHome.yaml
nm_tempalate_url: https://raw.githubusercontent.com/sloraris/ORBIT2.0/main/server_dns/template.nmconnection